---
- name: Setup tftp to backup NXOS's running-config
  hosts: localhost
  gather_facts: no
  become: yes

  tasks:
    - name: install xinetd & tftp-server
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - "xinetd"
        - "tftp-server"

    - name: make tftp_shared directory
      become: yes
      become_user: vagrant
      file:
        path: /home/vagrant/tftp_shared
        state: directory
        mode: 0777

    - name: replace tftp's config
      replace:
        path: "{{ item.path }}"
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      with_items:
        - { path: "/etc/xinetd.d/tftp", regexp: "root", replace: "vagrant" }
        - { path: "/etc/xinetd.d/tftp", regexp: "-s /var/lib/tftpboot", 
                   replace: "-c -p -u vagrant -s /home/vagrant/tftp_shared" }
    
    - name: modify tftp's config 
      lineinfile:
        path: /etc/xinetd.d/tftp
        regexp: 'disable'
        line: 'disable = disable'

    - name: modify tftp service's config
      replace:
        path: /usr/lib/systemd/system/tftp.service
        regexp: '-s /var/lib/tftpboot'
        replace: '-c -p -u vagrant -s /home/vagrant/tftp_shared'

    - name: selinux change to permissive on ansible-server
      selinux: policy=targeted state=permissive

    - name: service daemon restart
      systemd:
        state: restarted
        daemon_reload: yes
        name: tftp

    - name: xinetd service restart
      service:
        name: xinetd
        state: restarted


- name: Request to backup NXOS's running-config
  hosts: NXOS
  gather_facts: no

  tasks:
    - name: running-config backup #1
      delegate_to: 192.168.1.251
      run_once: true
      nxos_command:
        commands: 'copy running-config tftp://192.168.1.10/n9k-running-confg#1 
                   vrf management'

    - name: running-config backup #2
      delegate_to: 192.168.1.252
      run_once: true
      nxos_command:
        commands: 'copy running-config tftp://192.168.1.10/n9k-running-confg#2 
                   vrf management'

        
- name: Selinux restore on ansible-server
  hosts: localhost
  gather_facts: no
  become: yes
  tasks:
    - name: selinux change to enforcing
      selinux: policy=targeted state=enforcing