# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #==============#
  # CentOS nodes #
  #==============#
  
  #Ansible-Node101
  config.vm.define "ansible-node101" do |cfg|
     cfg.vm.box = "centos/7"
	 cfg.vm.provider "virtualbox" do |vb|
	   vb.name = "Ansible-Node101(github_SysNet4Admin)"
	 end
	 cfg.vm.host_name = "ansible-node101"
	 cfg.vm.network "public_network", ip: "192.168.1.101"
	 cfg.vm.network "forwarded_port", guest: 22, host: 60101, auto_correct: true, id: "ssh"
	 cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
	 cfg.vm.provision "shell", path: "bash_ssh_conf_4_CentOS.sh"
  end
  
  #Ansible-Node102	 
  config.vm.define "ansible-node102" do |cfg|
     cfg.vm.box = "centos/7"
	 cfg.vm.provider "virtualbox" do |vb|
	   vb.name = "Ansible-Node102(github_SysNet4Admin)"
	 end
	 cfg.vm.host_name = "ansible-node102"
	 cfg.vm.network "public_network", ip: "192.168.1.102"
	 cfg.vm.network "forwarded_port", guest: 22, host: 60102, auto_correct: true, id: "ssh"
	 cfg.vm.synced_folder "../data", "/vagrant", disabled: true
	 cfg.vm.provision "shell", path: "bash_ssh_conf_4_CentOS.sh"
  end

  #Ansible-Node103	 
  config.vm.define "ansible-node103" do |cfg|
     cfg.vm.box = "centos/7"
	 cfg.vm.provider "virtualbox" do |vb|
	   vb.name = "Ansible-Node103(github_SysNet4Admin)"
	 end
	 cfg.vm.host_name = "ansible-node103"
	 cfg.vm.network "public_network", ip: "192.168.1.103"
	 cfg.vm.network "forwarded_port", guest: 22, host: 60103, auto_correct: true, id: "ssh"
	 cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
	 cfg.vm.provision "shell", path: "bash_ssh_conf_4_CentOS.sh"
  end

  #Ansible-Node104	 
  config.vm.define "ansible-node104" do |cfg|
     cfg.vm.box = "centos/7"
	 cfg.vm.provider "virtualbox" do |vb|
	   vb.name = "Ansible-Node104(github_SysNet4Admin)"
	 end
	 cfg.vm.host_name = "ansible-node104"
	 cfg.vm.network "public_network", ip: "192.168.1.104"
	 cfg.vm.network "forwarded_port", guest: 22, host: 60104, auto_correct: true, id: "ssh"
	 cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
	 cfg.vm.provision "shell", path: "bash_ssh_conf_4_CentOS.sh"
  end

  #Ansible-Node105	 
  config.vm.define "ansible-node105" do |cfg|
     cfg.vm.box = "centos/7"
	 cfg.vm.provider "virtualbox" do |vb|
	   vb.name = "Ansible-Node105(github_SysNet4Admin)"
	 end
	 cfg.vm.host_name = "ansible-node105"
	 cfg.vm.network "public_network", ip: "192.168.1.105"
	 cfg.vm.network "forwarded_port", guest: 22, host: 60105, auto_correct: true, id: "ssh"
	 cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
	 cfg.vm.provision "shell", path: "bash_ssh_conf_4_CentOS.sh"
  end

  
  #==============#
  # Ubuntu nodes #
  #==============#
  
  #Ansible-Node201
  config.vm.define "ansible-node201" do |cfg|
     cfg.vm.box = "ubuntu/trusty64"
	 cfg.vm.provider "virtualbox" do |vb|
	   vb.name = "Ansible-Node201(github_SysNet4Admin)"
	 end
	 cfg.vm.host_name = "ansible-node201"
	 cfg.vm.network "public_network", ip: "192.168.1.201"
	 cfg.vm.network "forwarded_port", guest: 22, host: 60201, auto_correct: true, id: "ssh"
	 cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
  end
  
  #Ansible-Node202	 
  config.vm.define "ansible-node202" do |cfg|
     cfg.vm.box = "ubuntu/trusty64"
	 cfg.vm.provider "virtualbox" do |vb|
	   vb.name = "Ansible-Node202(github_SysNet4Admin)"
	 end
	 cfg.vm.host_name = "ansible-node202"
	 cfg.vm.network "public_network", ip: "192.168.1.202"
	 cfg.vm.network "forwarded_port", guest: 22, host: 60202, auto_correct: true, id: "ssh"
	 cfg.vm.synced_folder "../data", "/vagrant", disabled: true
  end

  #Ansible-Node203	 
  config.vm.define "ansible-node203" do |cfg|
     cfg.vm.box = "ubuntu/trusty64"
	 cfg.vm.provider "virtualbox" do |vb|
	   vb.name = "Ansible-Node203(github_SysNet4Admin)"
	 end
	 cfg.vm.host_name = "ansible-node203"
	 cfg.vm.network "public_network", ip: "192.168.1.203"
	 cfg.vm.network "forwarded_port", guest: 22, host: 60203, auto_correct: true, id: "ssh"
	 cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
  end

  #Ansible-Node204	 
  config.vm.define "ansible-node204" do |cfg|
     cfg.vm.box = "ubuntu/trusty64"
	 cfg.vm.provider "virtualbox" do |vb|
	   vb.name = "Ansible-Node204(github_SysNet4Admin)"
	 end
	 cfg.vm.host_name = "ansible-node204"
	 cfg.vm.network "public_network", ip: "192.168.1.204"
	 cfg.vm.network "forwarded_port", guest: 22, host: 60204, auto_correct: true, id: "ssh"
	 cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
  end

  #Ansible-Node205	 
  config.vm.define "ansible-node205" do |cfg|
     cfg.vm.box = "ubuntu/trusty64"
	 cfg.vm.provider "virtualbox" do |vb|
	   vb.name = "Ansible-Node205(github_SysNet4Admin)"
	 end
	 cfg.vm.host_name = "ansible-node205"
	 cfg.vm.network "public_network", ip: "192.168.1.205"
	 cfg.vm.network "forwarded_port", guest: 22, host: 60205, auto_correct: true, id: "ssh"
	 cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
  end
  
  
  #================#
  # Ansible Server #
  #================#
  
  config.vm.define "ansible-server" do |cfg|
    cfg.vm.box = "centos/7"
 	cfg.vm.provider "virtualbox" do |vb|
	  vb.name = "Ansible-Server(github_SysNet4Admin)"
	end
	cfg.vm.host_name = "ansible-server"
	cfg.vm.network "public_network", ip: "192.168.1.10"
	cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"
	cfg.vm.synced_folder "../data", "/vagrant", disabled: true
	cfg.vm.provision "shell", inline: "yum install epel-release -y"
	cfg.vm.provision "shell", inline: "yum install ansible -y"
	cfg.vm.provision "file", source: "ansible_env_ready.yml", 
	  destination: "ansible_env_ready.yml"
	cfg.vm.provision "shell", inline: "ansible-playbook ansible_env_ready.yml"
  end
end