- name: install epel-release for {{ ansible_distribution }}
  action: "{{ ansible_pkg_mgr }} name=epel-release state=latest"
- name: install nginx web server for {{ ansible_distribution }}
  action: "{{ ansible_pkg_mgr }} name=nginx state=present"