---
- name: Install nginx on the nodes
  hosts: nodes
  become: yes
  vars:
    nu: "{{ groups.nodes | count }}"
    idx: "{{ groups.nodes.index(inventory_hostname)+1 | int }}"
    lnx_name: "{{ 'CentOS' if ansible_distribution == 'CentOS'
                   else 'Ubuntu' if ansible_distribution == 'Ubuntu'
                   else 'Just Linux' }}"

  tasks:
    - name: nginx for any linux
      include_tasks: "{{ lnx_name }}.yml"
      
    - name: create web page for each node
      template:
        src: index.j2
        dest: /usr/share/nginx/html/index.html
        mode: 0644
        backup: yes

    - name: check nginx service
      debug: msg="{{lookup('template','ins_chk.j2').split('\n')}}"
        
  handlers:
    - name: restart nginx web server
      service: name=nginx state=restarted
