---
- name: Setup NXOS timezone with ntp configuration
  hosts: NXOS
  gather_facts: no

  tasks:
    - name: ntp configuration
      nxos_config:
        lines: 'ntp server 192.168.1.10 use-vrf management'
        save_when: modified

    - name: timezone to UTC 9 0
      nxos_config:
        lines: 'clock timezone UTC 9 0'
        save_when: modified