# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #============#
  # VyOS Nodes #
  #============#
  
  #Ansible-VyOS01
  config.vm.define "ansible-vyos01" do |vy|
	 vy.vm.box = "sysnet4admin/VyOS"
	 vy.vm.provider "virtualbox" do |vb|
	   vb.name = "Ansible-VyOS01(github_SysNet4Admin)"
	 end
	 vy.vm.host_name = "ansible-vyos01"
	 vy.vm.network "public_network", ip: "192.168.1.51"
	 vy.vm.network "forwarded_port", guest: 22, host: 60051, auto_correct: true, id: "ssh"
	 vy.vm.network "private_network", virtualbox__intnet: "eth2", auto_config: false
	 vy.vm.network "private_network", virtualbox__intnet: "eth3", auto_config: false
     vy.vm.synced_folder "../data", "/vagrant", disabled: true 
	 vy.vbguest.auto_update = false
  end

  #Ansible-VyOS02
  config.vm.define "ansible-vyos02" do |vy|
	 vy.vm.box = "sysnet4admin/VyOS"
	 vy.vm.provider "virtualbox" do |vb|
	   vb.name = "Ansible-VyOS02(github_SysNet4Admin)"
	 end
	 vy.vm.host_name = "ansible-vyos02"
	 vy.vm.network "public_network", ip: "192.168.1.52"
	 vy.vm.network "forwarded_port", guest: 22, host: 60052, auto_correct: true, id: "ssh"
	 vy.vm.network "private_network", virtualbox__intnet: "eth2", auto_config: false
	 vy.vm.network "private_network", virtualbox__intnet: "eth3", auto_config: false
     vy.vm.synced_folder "../data", "/vagrant", disabled: true 
	 vy.vbguest.auto_update = false
  end
  
  #================#
  # Ansible Server #
  #================#
  
  config.vm.define "ansible-server" do |cfg|
    cfg.vm.box = "centos/7"
 	cfg.vm.provider "virtualbox" do |vb|
	  vb.name = "Ansible-Server(github_SysNet4Admin)"
	end
	cfg.vm.host_name = "ansible-server"
	cfg.vm.network "public_network", ip: "192.168.1.10"
	cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"
	cfg.vm.synced_folder "../data", "/vagrant", disabled: true
	cfg.vm.provision "shell", inline: "yum install epel-release -y"
	cfg.vm.provision "shell", inline: "yum install ansible -y"
	cfg.vm.provision "file", source: "ansible_env_ready.yml", 
	  destination: "ansible_env_ready.yml"
	cfg.vm.provision "shell", inline: "ansible-playbook ansible_env_ready.yml"
  end
end
