- name: install xinetd & tftp-server
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "xinetd"
    - "tftp-server"

- name: make tftp_shared directory
  become: yes
  become_user: vagrant
  file:
    path: /home/vagrant/tftp_shared
    state: directory
    mode: 0777

- name: replace tftp's config
  replace:
    path: "{{ item.path }}"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - { path: "/etc/xinetd.d/tftp", regexp: "root", replace: "vagrant" }
    - { path: "/etc/xinetd.d/tftp", regexp: "-s /var/lib/tftpboot", 
               replace: "-c -p -u vagrant -s /home/vagrant/tftp_shared" }

- name: modify tftp's config 
  lineinfile:
    path: /etc/xinetd.d/tftp
    regexp: 'disable'
    line: 'disable = disable'

- name: modify tftp service's config
  replace:
    path: /usr/lib/systemd/system/tftp.service
    regexp: '-s /var/lib/tftpboot'
    replace: '-c -p -u vagrant -s /home/vagrant/tftp_shared'
