---
- name: Setup for the frr's config
  hosts: cl
  gather_facts: no
  become: yes

  tasks:
    - name: modify /etc/frr/daemons
      replace:
        path: /etc/frr/daemons
        regexp: 'zebra=no'
        replace: 'zebra=yes'

    - name: frr service enable and restart
      service:
        name: frr
        enabled: yes
        state: restarted